### ISSUE TITLE
دو مورد نیاز به بررسی

### ISSUE THREAD

**Issue by 0g0** [desmati/persian-angular-date-picker#1]
سلام و خسته نباشید

مورد اول مربوط به بستن ایونت کلیک تگ اچ تی ام ال هست در قطعه کد

htmlTag.on('click', function (e) {
                scope.hide();
                return false;
            });

برگشت مقدار فالس باعث عدم ادامه ایونت های از قبل تعریف شده می شود. لازم است خط
return false
حذف شود

مورد دوم مربوط به تعیین مکان پاپ آپ هست در قطعه کد

scope.show = function () {
                var box = txtBox[0];
                var picker = datePicker;
                picker.removeClass("ng-hide");
                //var offsetBox = offset(txtBox[0]);
                //var left = offsetBox.left + box.clientWidth - datePicker[0].clientWidth + 4;
                //var top = offsetBox.top + box.clientHeight + 4;
                //datePicker.css({ 'left': left.toString() + "px", 'top': top.toString() + "px" });
            }

بخش کامنت شده وابسته به کد ها و استایل های تعریف شده است و حالت کلی ندارد. یعنی محل نمایش پاپ آپ می تواند اشتباه باشد

**Comment by desmati** [comment]
ممنون میشم اگر تغییرات مورد نیاز رو انجام بدید و پوش کنید تا پروژه رو آپدیت کنم.
